---
- name: install start and enable httpd
  gather_facts: false
  hosts: target1
  tasks:
  - name: install package
    package:
      name: httpd
      state: latest
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes

- name: test httpd accessibility
  become: False
  hosts: localhost
  tasks:
  - name: test httpd access
    uri:
      url: http://192.168.0.241
